name: GitHub-Profile-3D-Contrib

on:
  push:
    branches:
      - main
    paths-ignore:
      - "profile-3d-contrib/*.svg"
    # paths:
    #   - .github/workflows/profile-3d.yml

  # pull_request: need to set head_ref
  #   branches:
  #     - main

  schedule: # 00:00 IST == 05:30 UTC
    - cron: "10 */1 * * *"
    # 00:00 IST == 05:30 UTC
    - cron: "30 5 * * *"
  workflow_dispatch:

concurrency:
  group: git-commit
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          SETTING_JSON: profile-3d-contrib/hiro-rainbow.json

      # - name: Commit & Push
      #   run: |
      #     git config user.name Baymax
      #     git config user.email laciferin@gmail.com
      #     git add -A .
      #     git commit -m "update: profile-3d"
      #     git push

      - name: Git Status
        continue-on-error: true
        run: |
          git status
          git pull

      - uses: stefanzweifel/git-auto-commit-action@v5
        id: auto-commit
        with:
          commit_user_name: Baymax
          commit_user_email: laciferin@gmail.com
          commit_author: Hiro <laciferin@gmail.com>
          commit_message: "ci: update profile-3d"
          commit_options: "--no-verify --signoff"
          add_options: "-A"
          # file_pattern: "profile-3d-contrib/*.svg" #TODO:
          file_pattern: "profile-3d-contrib/profile-night-rainbow.svg"
          skip_checkout: true
          create_branch: false

      - name: "Run if changes have been detected"
        if: steps.auto-commit.outputs.changes_detected == 'true'
        run: echo "Changes!"

      - name: "Run if no changes have been detected"
        if: steps.auto-commit.outputs.changes_detected == 'false'
        run: echo "No Changes!"

      - uses: vimtor/action-zip@v1.1
        with:
          files: ${{github.workspace}}/profile-3d-contrib
          recursive: true
          dest: profile-3d-contrib.zip

      - uses: actions/upload-artifact@v3
        with:
          name: profile-3d-contrib.zip
          path: ${{ github.workspace }}/profile-3d-contrib.zip
